<?php
/**
 * @author Andrey Bondarenko
 * @link http://encomage.com
 * @mail info@encomage.com
 */

/** @var \Encomage\StoreLocator\Block\Widget\StoreLocator $block */
?>
<?php if ($block->getLabel()): ?>
    <p><?php echo $block->escapeHtml($block->getLabel()); ?></p>
<?php endif; ?>
<?php if ($block->isShowMarkersList()): ?>
    <?php $markersCollection = $block->getCollection(); ?>
    <?php if ($markersCollection->getSize()): ?>
        <?php foreach ($markersCollection as $marker): ?>
            <div
                class="js-show-marker store-locator-widget"
                data-marker-id="<?php echo (int)$marker->getId() ?>">
                <?php echo $block->escapeHtml($marker->getName()); ?>
            </div>
        <?php endforeach; ?>
    <?php endif; ?>
<?php endif; ?>
<div <?php /* @escapeNotVerified */ echo $block->getMapBlockAttributes(); ?>></div>
<script type="text/x-magento-init">
  <?php
    /* @escapeNotVerified */
    echo $this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode(
        [
            '*' => [
                'Encomage_StoreLocator/js/locator' => $block->getParams()
            ],
        ]
    );
    ?>
</script>