<?php
/**
 * @author Andrey Bondarenko
 * @link http://encomage.com
 * @mail info@encomage.com
 */

/** @var \Encomage\StoreLocator\Block\Widget\StoreLocator $block */
?>

<div><?php  $block->getTest();?></div>
<div id="<?php echo $block->escapeHtml($block->getMapContainerId()); ?>" style="      height: 400px;
        width: 100%;"></div>
<script type="text/x-magento-init">
  <?php
    /* @escapeNotVerified */
    echo $this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode(
        [
            '*' => [
                'Encomage_StoreLocator/js/locator' => $block->getParams()
            ],
        ]
    );
    ?>
</script>